quarkus.http.port=8081

# OpenAPI / Swagger
mp.openapi.extensions.smallrye.info.version=1.0.0
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Health
quarkus.smallrye-health.root-path=/q/health
