<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.mscreditevaluation</groupId>
        <artifactId>ms-credit-evaluation</artifactId>
        <version>1.0.0-SNAPSHOT</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>
    <groupId>com.mscreditevaluation.app</groupId>
    <artifactId>infrastructure-entry-points-app</artifactId>
    <dependencies>
        <dependency>
            <groupId>com.mscreditevaluation.restapi</groupId>
            <artifactId>infrastructure-entry-points-rest-api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mscreditevaluation.usecases</groupId>
            <artifactId>application-use-cases</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mscreditevaluation.postgres</groupId>
            <artifactId>infrastructure-driven-adapters-postgres</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.mscreditevaluation.sqsproducer</groupId>
            <artifactId>infrastructure-driven-adapters-sqs-producer</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-jwt</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mscreditevaluation.riskclient</groupId>
            <artifactId>infrastructure-driven-adapters-risk-service-client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <!-- Test -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-security-jwt</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock-standalone</artifactId>
            <version>3.3.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-devservices-postgresql</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>io.quarkus.platform</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemPropertyVariables>
                    <includes>
                        <include>**/*IT</include>
                        <include>**/*IT.java</include>
                        <include>**/*IT.class</include>
                    </includes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
